[package]
name = "tea_vault_jedi_v2"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html


[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs-list.name = "all"
build-external-contracts = [
    "openzeppelin::presets::erc20::ERC20",
    "jediswap_v2_core::jediswap_v2_pool::JediSwapV2Pool",
    "jediswap_v2_core::jediswap_v2_factory::JediSwapV2Factory",
    "jediswap_v2_periphery::jediswap_v2_nft_position_manager::JediSwapV2NFTPositionManager"
]

[dependencies]
starknet = ">=2.4.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.16.0" }
yas_core = { git = "https://github.com/lambdaclass/yet-another-swap.git" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }
jediswap_v2_core = { path = "../JediSwap-v2-core" }
jediswap_v2_periphery = { path = "../JediSwap-v2-periphery" }
# jediswap_v2_core = { git = "https://github.com/jediswaplabs/JediSwap-v2-core.git" }
# jediswap_v2_periphery = { git = "https://github.com/jediswaplabs/JediSwap-v2-periphery.git" }